spring.application.name=ContactsApp

# H2 in-memory database configuration
spring.datasource.url=jdbc:h2:mem:contactsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

#runs this app on 8082 when 8080 is busy
server.port=8082

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
